### ISSUE TITLE
WordPress 5.6 のエディタで動作しない

### ISSUE THREAD

**Issue by chiilabo** [technote-space/change-block-keywords#264]
こんにちは。
WordPress 5.6 にアップデートしたところ、
スラッシュで開始するブロック候補が
プラグイン導入前に戻ってしまいました。

どうも、change-block-keywordsの処理が
呼び出されなくなっているようです。
（呼び出し関数名が変わった？）

いったん、WordPress 5.5.3 に復元して利用していますが、
WordPress 5.6 へ対応していただけると嬉しいです。

どうぞよろしくお願いいたします。

**Comment by technote-space** [comment]
@chiilabo 
報告ありがとうございます。
プラグインのバージョンを教えていただけますか？

**Comment by chiilabo** [comment]
いつもほんとに助かってます！ありがとうございます。

プラグイン画面では、「バージョン 2.1.1 」と表記されています。
わたしの今のWordPressバージョンは5.5.3で、ここまでは正常に動作していました。
最新の5.6には対応していないようです。

---
バージョン: 2.1.1
投稿者: Technote
対応する最新バージョン: 5.4.999

**Comment by technote-space** [comment]
Gutenbergプラグインですでに5.6に対応しているはずだと思いましたが、一応手元のWP5.6とプラグインで確認しました。
結果として再現できていないため、今の情報だけだと対応はできません。

使用しているプラグインやテーマ、ブラウザなどの情報で再現する条件が分かる可能性はありますが、OSSの性質上こちらでその条件を見つける作業はできません。
対応が必要な場合は再現できる情報をいただければと思います。
よろしくおねがいします。

**Comment by chiilabo** [comment]
返信ありがとうございます。

確かに、WP5.5と5.6で、ブロックエディタに大きな変更点はないですよね。
WordPress 5.6でも動作することを伺い、安心しました。

こちらでもう一度アップグレードして、プラグインやテーマなどを確認してみます。
テーマはCocoonです。プラグインがキャッシュ系が関係しているかもしれません。
原因がわかりましたら、報告いたします。

**Comment by chiilabo** [comment]
大変申し訳ないです。再度、アップグレードしたら、正常に動作しました。
アップグレードの方がうまくいっていなかったようです。

お騒がせしましたm(_ _)m
